import { Space_Mono } from "next/font/google";
import "~/styles/globals.css";

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className} bg-[#FFF0F3] text-zinc-800`}>
        {children}
      </body>
    </html>
  );
}
