import { Merriweather } from "next/font/google";
import "~/styles/globals.css";

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-brown-100 text-brown-800`}>
        {children}
      </body>
    </html>
  );
}
